/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as PaymentResultRouteImport } from './routes/payment-result'
import { Route as PrescriptionRouteImport } from './routes/prescription'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TryOnRouteImport } from './routes/try-on'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiPublicPaymentsBkashRouteImport } from './routes/api/public/payments/bkash'
import { Route as ApiPublicPaymentsSslcommerzRouteImport } from './routes/api/public/payments/sslcommerz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentResultRoute = PaymentResultRouteImport.update({
  id: '/payment-result',
  path: '/payment-result',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionRoute = PrescriptionRouteImport.update({
  id: '/prescription',
  path: '/prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TryOnRoute = TryOnRouteImport.update({
  id: '/try-on',
  path: '/try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsBkashRoute = ApiPublicPaymentsBkashRouteImport.update({
  id: '/api/public/payments/bkash',
  path: '/api/public/payments/bkash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsSslcommerzRoute =
  ApiPublicPaymentsSslcommerzRouteImport.update({
    id: '/api/public/payments/sslcommerz',
    path: '/api/public/payments/sslcommerz',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/payment-result': typeof PaymentResultRoute
  '/prescription': typeof PrescriptionRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRoute
  '/try-on': typeof TryOnRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/payments/bkash': typeof ApiPublicPaymentsBkashRoute
  '/api/public/payments/sslcommerz': typeof ApiPublicPaymentsSslcommerzRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/payment-result': typeof PaymentResultRoute
  '/prescription': typeof PrescriptionRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRoute
  '/try-on': typeof TryOnRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/payments/bkash': typeof ApiPublicPaymentsBkashRoute
  '/api/public/payments/sslcommerz': typeof ApiPublicPaymentsSslcommerzRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/payment-result': typeof PaymentResultRoute
  '/prescription': typeof PrescriptionRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRoute
  '/try-on': typeof TryOnRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/payments/bkash': typeof ApiPublicPaymentsBkashRoute
  '/api/public/payments/sslcommerz': typeof ApiPublicPaymentsSslcommerzRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/payment-result'
    | '/prescription'
    | '/shop'
    | '/track'
    | '/try-on'
    | '/product/$id'
    | '/api/public/payments/bkash'
    | '/api/public/payments/sslcommerz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/payment-result'
    | '/prescription'
    | '/shop'
    | '/track'
    | '/try-on'
    | '/product/$id'
    | '/api/public/payments/bkash'
    | '/api/public/payments/sslcommerz'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/payment-result'
    | '/prescription'
    | '/shop'
    | '/track'
    | '/try-on'
    | '/product/$id'
    | '/api/public/payments/bkash'
    | '/api/public/payments/sslcommerz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  PaymentResultRoute: typeof PaymentResultRoute
  PrescriptionRoute: typeof PrescriptionRoute
  ShopRoute: typeof ShopRoute
  TrackRoute: typeof TrackRoute
  TryOnRoute: typeof TryOnRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiPublicPaymentsBkashRoute: typeof ApiPublicPaymentsBkashRoute
  ApiPublicPaymentsSslcommerzRoute: typeof ApiPublicPaymentsSslcommerzRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-result': {
      id: '/payment-result'
      path: '/payment-result'
      fullPath: '/payment-result'
      preLoaderRoute: typeof PaymentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription': {
      id: '/prescription'
      path: '/prescription'
      fullPath: '/prescription'
      preLoaderRoute: typeof PrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try-on': {
      id: '/try-on'
      path: '/try-on'
      fullPath: '/try-on'
      preLoaderRoute: typeof TryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/bkash': {
      id: '/api/public/payments/bkash'
      path: '/api/public/payments/bkash'
      fullPath: '/api/public/payments/bkash'
      preLoaderRoute: typeof ApiPublicPaymentsBkashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/sslcommerz': {
      id: '/api/public/payments/sslcommerz'
      path: '/api/public/payments/sslcommerz'
      fullPath: '/api/public/payments/sslcommerz'
      preLoaderRoute: typeof ApiPublicPaymentsSslcommerzRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  PaymentResultRoute: PaymentResultRoute,
  PrescriptionRoute: PrescriptionRoute,
  ShopRoute: ShopRoute,
  TrackRoute: TrackRoute,
  TryOnRoute: TryOnRoute,
  ProductIdRoute: ProductIdRoute,
  ApiPublicPaymentsBkashRoute: ApiPublicPaymentsBkashRoute,
  ApiPublicPaymentsSslcommerzRoute: ApiPublicPaymentsSslcommerzRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
